version: '3'

services:
  codelab-app:
    container_name: codelab-app
    build:
      context: .docker/node
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    entrypoint: .docker/node/entrypoint.sh  
    volumes: 
      - .:/home/node/app
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGDATABASE=codelab
      - PGPORT=5432
    ports: 
      - '3000:3000'

  # codelab-pg:
  #   container_name: codelab-pg
  #   image: postgres:16.2
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #   volumes:
  #     - '.data:/var/lib/postgresql/data'
  #   ports:
  #     - '5433:5432'

  db:
    container_name: db
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all
    volumes:
      - '.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432